spring:
  application:
    name: youth-health-backend
  profiles:
    active: dev

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.youthhealth.modules
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
